### ISSUE TITLE
Editing Term field (such as label) doesn't replace content, but adds additional literal

### ISSUE THREAD

**Issue by wickr** [OregonDigital/ControlledVocabularyManager#125]
This happens both in the web interface as well as the Rails console. Persist! says true but nothing is deleted.

```
irb(main):001:0> js = Term.find('localCollectionName/p_052')
=> #<Term:0x3fcd206c7118(default)>
irb(main):001:0> js.graph.delete([nil, RDF::URI.new("http://www.w3.org/2001/XMLSchema#date"), nil])
=> #<Term:0x3fcd206c7118(default)>
irb(main):001:0> js.persist!
=> true
```

(the originally mentioned term at http://opaquenamespace.org/ns/localCollectionName/rg_258 is now fixed)

**Comment by wickr** [comment]
I think it's related to this bug: https://issues.apache.org/jira/browse/MARMOTTA-528

**Comment by revgum** [comment]
I believe this is fixed. I'm unable to reproduce it locally. I suspected this was having to do with the "Versioning" configuration for Marmotta, but testing it enabled and disabled did not reproduce the bug.

**Comment by revgum** [comment]
I've been able to reproduce the effect with both Marmotta and Blazegraph as the backend triplestore. The bottom line is, we have a repository tied to each of our classes that persist to the triplestore. When submitting a form to update a term(or vocab, etc), the repository first wants to delete the existing term in the triplestore and insert the term with it's updated rdf statements.. The delete API isn't fully baked in our implementation using Marmotta. I've been able to get the delete working (for a vocab) for Blazegraph, which makes the process for a vocab work appropriately. On the other hand, deleting a term (a child of a vocab) isn't working properly with the rdf-blazegraph gem that I've been using. 

The future approach that I think would be worthwhile is to continue the migration to Blazegraph, and to implement the delete properly for terms (children of vocabs). And then to consider when updating a term to only delete statements that were in the triplestore but not posted on the form (because they were removed), and submitting statements which had updated objects (label, etc) instead of deleting all of the statements and re-inserting them.

**Comment by wickr** [comment]
Direct SPARQL delete queries in Marmotta are a workaround for now.

**Comment by wickr** [comment]
We believe this was fixed by Brandon as a form fix that got into the Blazegraph branch, need to double check once that is all deployed.

**Comment by mickeroo** [comment]
Has this been fixed?
