### ISSUE TITLE
Child Terms list should sort by Title/Label, not URI value

### ISSUE THREAD

**Issue by wickr** [OregonDigital/ControlledVocabularyManager#456]
Any vocabulary with children that use opaque ids doesn't have a sensible sort when using the URI value. (OSU Academic Units)
Others with some mixed (localCollectionName) also look ok at first but don't hold the sort for the whole list.

Probably can just modify this:
https://github.com/OregonDigital/ControlledVocabularyManager/blob/master/app/services/child_node_finder.rb#L10

**Comment by straleyb** [comment]
@wickr Can you post some of the results or different types of child terms that will exist for a vocabulary? Im curious if we can parse away the URI's and leave just the term id and sort on those. Is that the desired result. Otherwise, I would imagine we can sort when it populates the list based on title.

**Comment by wickr** [comment]
@straleyb the term id is parsed out and sorted on now: http://opaquenamespace.org/ns/osuDegreeFields

But especially as we're using some opaque ids, sorting on those doesn't make sense.

You might be able to just change `rdf_subject` to `rdf_object` on this line: https://github.com/OregonDigital/ControlledVocabularyManager/blob/master/app/services/child_node_finder.rb#L10

but I haven't tested that.
