### ISSUE TITLE
Issues with Setup

### ISSUE THREAD

**Issue by brimwats** [OregonDigital/ControlledVocabularyManager#534]
Hello,

Forgive me if this is unclear, as I've taught myself literally everything I know about ruby to get to the point of having this work. The installation guide isn't super through and I'd be happy to provide more steps for someone coming after (f.ex., it breaks on clean vagrant up and cmake/python2.5.1/rugged/something else needs to be installed and then you can vagrant up again). 

After following the vagrant steps (and still having fails) I just had to do the manual steps rake db:create && rake db:migrate / rake triplestore_adapter:blazegraph:reset / rake sunspot:solr:start (this also fails unless you start solr first) and I finally got the frontend for the CVM to start. 

However the jetty aspect seems completely broken -- whenever I try to access blazebraph at 9999 I get a 404 i get this issue https://sourceforge.net/p/bigdata/discussion/676946/thread/61163769/?limit=25 but the solution there is incredibly vague for someone who hasn't been in the coding world for long.

I want to use the CVM to make a similar website to homosaurus, except with more sex/uality nomenclature.

Thank you for your time!

**Comment by wickr** [comment]
Hi @brimwats thanks for your feedback.

I apologize for the installation confusion. The Vagrant instructions and scripts are really old and out-of-date. You're right that the Vagrant jetty part is broken, those specific scripts were needed for the triplestore software (Marmotta) that we used before Blazegraph.

It looks like you had some success with the manual steps though. If the Vagrant parts (and jetty) are all shut down, you should be able to run `rake triplestore_adapter:blazegraph:reset` and get Blazegraph to start up. You should see messages similar to this:
```
Starting Blazegraph server
Blazegraph started on PID 12820
Waiting for Blazegraph server to settle
Building test namespace
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9999 (#0)
> POST /blazegraph/namespace HTTP/1.1
> Host: localhost:9999
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Type:text/plain
> Content-Length: 35
> 
* upload completely sent off: 35 out of 35 bytes
< HTTP/1.1 201 Created
< Content-Type: text/plain; charset=ISO-8859-1
< Location: http://localhost:9999/blazegraph/namespace/test/sparql
< Content-Length: 13
< Server: Jetty(9.2.z-SNAPSHOT)
< 
* Connection #0 to host localhost left intact
CREATED: test

Yay! Blazegraph should be ready to roll.
```
Then you should be able to visit localhost:9999 and see the Blazegraph Workbench loaded. (Regular use of CVM doesn't require using this Blazegraph interface, but it can be helpful to check if things are working correctly).

Another step that is not in the manual setup section that you may need is:
`rake git_dev:create_dev_repo`
(this initializes an empty Git source control repository where data for the terms you enter is also stored).

Hopefully this gets it all running, or at least much closer to it. Let me know.

**Comment by brimwats** [comment]
@wickr thanks a lot! It still seems to fail by following the instructions (I'll leave my terminal dump below) but I finally got it to work. It seems that I overestimated all of ON's features, as I thought there might be a place to create vocabularies from, but I see that's not the case! 

I understand that it is definite;y not your job to babysit someone just tinkering when you're trying to update ON for Oregon, but if you wouldn't mind ,I would love to know where you push the competed vocabularies to on ON & from what for something like homosaurus?

As promised here is the terminal dump. There is likely something basic I missed, but if you see anything useful for instructions here you go:


[opaquenamespace.txt](https://github.com/OregonDigital/ControlledVocabularyManager/files/3204752/opaquenamespace.txt)

**Comment by brimwats** [comment]
ah, I see you've removed the vagrant section. Perhaps my errors were from vagrant itself then!

**Comment by wickr** [comment]
Yes, it does look like you have Blazegraph running successfully at the end of the terminal dump. Although, some of the earlier tasks didn't complete successfully, apparently because Blazegraph wasn't loaded yet (the connection refused errors), so we have the order wrong. If you still have the Rails server running, stop that (`Ctrl-C` on the keyboard should do it). Blazegraph should still be running, so run these 3 tasks again one at a time:
```
rake db:create && rake db:migrate
rake git_dev:create_dev_repo
rake sunspot:solr:start
```
(they will each have different output, but you shouldn't see any more connection refused errors. The last one should just output 'Successfully started Solr')

Now run `rails server` again to bring up the application.

You said that you do not see a place to create vocabularies, I think the missing part is creating an admin-level user that has privileges to create a vocabulary. This is a manual process right now, but here's the steps:

Click Login in the top-right. On that page, click 'Sign up'. Fill out the form and submit. Now it should show you are logged in, but you won't yet have permissions.
Switch back to your terminal, and open another one (leaving the one running the Rails server). Start a Rails console with `rails console`

Then type `me = User.first` hit enter, and you should see a User object with your name and other details.
Then type `me.role = "admin reviewer editor"` and hit enter
Then type `me.save` and hit enter

Now go back to the application in the browser. Refresh, and you should see some changes. If you go to the Vocabularies page, you should now see a button below the heading that says 'Create Vocabulary' which will take you to the form you can fill out.

I'm not sure what exactly you're asking or referring to about pushing vocabularies. We publish them at opaquenamespace.org and then our applications like Oregon Digital (oregondigital.org) can pull in specific terms, or whole vocabularies, as needed using linked data. But our Vocabularies and associated Terms are created, edited and managed on opaquenamespace.org. 
I don't know much about how Homosaurus operates really. Other than they split off from this code a few years ago and made several enhancements.

**Comment by brimwats** [comment]
@wickr that worked absolutely perfectly and your explanation was clear! I really appreciate it and I'm looking forward to digging into Opaque Namsepace!

By push I did mean publish, but it was originating from a misunderstanding. It looks like this will work perfectly. If I can be of any help to you, please let me know. I will let y'all here know if I notice anything else broken or needing updating. Thank you again for taking the time to help!
